# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
          main:
              entity:
                  class:    UserBundle\Entity\User
                  property: email

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        UserBundle\Entity\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
         dev:
             pattern: ^/(_(profiler|wdt)|css|images|js)/
             security: false

         main:
             pattern:   ^/
             anonymous: true
             provider:  main
             form_login:
                 login_path: login
                 check_path: login_check
             logout:
                 path:       logout
                 target:     login

    role_hierarchy :
        ROLE_MODO : ROLE_USER
        ROLE_ADMIN : [ROLE_USER, ROLE_MODO]